[package]
name = "qw-parquet-tantivy-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrow = { version = "14.0.0" }
parquet = "14.0.0"
tantivy = "0.17.0"
